---

- name: vlan provisioning
  hosts: automation-switches
  gather_facts: true
  connection: local

  vars:
    vlan_id: 999
    vlan_name: Ansible_VLAN_999
    cli:
       authorize: yes
       auth_pass: cisco

  tasks:
    - name: Configure VLAN ID
      ios_config:
        provider: "{{ cli }}"
        lines:
          - vlan {{ vlan_id }}
      register: configure_vlan

    - name: Configure VLAN Name
      ios_config:
        provider: "{{ cli }}"
        lines:
          - name {{ vlan_name }}
        parents: vlan {{ vlan_id }}

    - name: Show VLAN
      ios_command:
        provider: "{{ cli }}"
        commands:
          - show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
